### ISSUE TITLE
watchOS 8.1

### ISSUE THREAD

**Issue by davidseek** [filsv/watchOSDeviceSupport#1]
Can we add support for 8.1? Need it right now

**Comment by superarts** [comment]
Could you add watchOS 8.5 please?

**Comment by filsv** [comment]
@davidseek Try to use 8.3 instead, should work: [Download](https://github.com/filsv/watchOSDeviceSupport/raw/master/8.3.zip).

**Comment by filsv** [comment]
@superarts Sure, here is WatchOS 8.5 Support Files - [Download](https://github.com/filsv/watchOSDeviceSupport/raw/master/8.5.zip).
