### ISSUE TITLE
please help me with watch9.5 support files

### ISSUE THREAD

**Issue by crosstmh** [filsv/watchOSDeviceSupport#4]
thank you ~~

**Comment by joshuabeeler** [comment]
Me too! 🙏

**Comment by abouzaidan-tony** [comment]
Same here!!

**Comment by PiaoL** [comment]
Same Please, 🙏

**Comment by filsv** [comment]
@crosstmh @joshuabeeler @abouzaidan-tony @PiaoL Hello guys, please use [9.4](https://github.com/filsv/watchOSDeviceSupport/raw/master/9.4.zip) support files, it should be working with WatchOS 9.4,9.5,9.6 as @chatchavan mentioned [here](https://github.com/filsv/watchOSDeviceSupport/pull/5#issue-1850523929).
