### ISSUE TITLE
WatchOS 8.8.1

### ISSUE THREAD

**Issue by AltairBurton** [filsv/watchOSDeviceSupport#6]
Hi ! 
I'm currently experiencing a problem since I updated my apple watch 3 to version 8.8.1 . I can no longer install my app with my Xcode (version 14.2 on MacOS 12.6.3 - Monterey). I have this issue : "Unable to load development services" .
Do you have version 8.8 - Xcode WatchOS DeviceSupport ? I can't find it and I think it might help me solve my problem. 
Thanks and best Regards

**Comment by filsv** [comment]
@AltairBurton Hello, please try to use [8.7](https://github.com/filsv/watchOSDeviceSupport/raw/master/8.7.zip) or [9.0](https://github.com/filsv/watchOSDeviceSupport/raw/master/9.0.zip) and let me know if it's work, feel free to reopen the issue if it's not helped.
